name: Deploy Continuum API to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Build and Push Docker Image
        run: |-
          gcloud builds submit ./api \
            --tag "gcr.io/${{ secrets.GCP_PROJECT_ID }}/continuum-api:latest"

      - name: Deploy to Cloud Run
        run: >
          gcloud run deploy continuum-api
          --image "gcr.io/${{ secrets.GCP_PROJECT_ID }}/continuum-api:latest"
          --region "asia-southeast2"
          --platform "managed"
          --allow-unauthenticated
          --set-env-vars "SUPABASE_URL=${{ secrets.SUPABASE_URL }},SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }},NODE_ENV=production"
          --labels="goog-managed-by=cloudfunctions"