name: Supabase DB Migration

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/**'

jobs:
  migrate-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Prefer IPv4 for network connections
        run: echo "precedence ::ffff:0:0/96  100" | sudo tee -a /etc/gai.conf

      - name: Push Database Migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          echo "Pushing migrations to production..."
          supabase db reset --db-url "$SUPABASE_DB_URL"
