name: Deploy Continuum Dashboard to Firebase

on:
  push:
    branches:
      - main
    paths:
      - 'dashboard/**'

jobs:
  deploy-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Or your preferred LTS version

      - name: Install and Build Dashboard
        run: |
          cd dashboard
          npm install
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTINUUM }}'
          channelId: live
          projectId: continuum # Replace with your Firebase Project ID
          entryPoint: ./dashboard